server:
  port: 8081

logging:
  level:
    root: info
    com.example.standardproject: DEBUG
    org.springframework.web.client.RestTemplate: DEBUG

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/student_management
    username:
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        generate_statistics: true

  application:
    name: ecommerce_project